clone_depth: 1
image: Visual Studio 2019
cache:
  - packages -> appveyor.yml
environment:
  environment:
  matrix:
    - job_name: VS 16 2019 / python 3.8
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CMAKE_GENERATOR: Visual Studio 16 2019
      PYTHON: "C:\\Python38-x64"

install:
    # Prepend the selected Python to the PATH of this build
    - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
    # Display version information about selected python and pip
    - python --version
    - python -c "import sys, platform, struct;
      print(sys.platform, platform.machine(), struct.calcsize('P')*8)"
    - pip --version
    - pip install mako
before_build:
    - git submodule update --init --recursive
    - cmake -G "%CMAKE_GENERATOR%" -A x64 \
        -DCMAKE_BUILD_TYPE:STRING=Release -DENABLE_ORC:BOOL=OFF -DENABLE_TESTING:BOOL=ON \
        .
build_script:
    - cmake --build . --config Release --target INSTALL
test_script:
    - ctest -V --output-on-failure -C Release
after_test:
    - cd "c:\Program Files"
    - 7z a "c:\libvolk-x64-%VC_VERSION%.zip" volk
    - mkdir dlls
    - cd dlls
    - 7z a "c:\libvolk-x64-deps-%VC_VERSION%.zip" *
    - appveyor PushArtifact c:\libvolk-x64-%VC_VERSION%.zip
    - appveyor PushArtifact c:\libvolk-x64-deps-%VC_VERSION%.zip
